name: adamvilliers
favicon: null
layout_spectrum: 0.31418726057745516
typography_spectrum: 0.2501019991468638
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.010557514615356922
  lightness: 0.7370277459267527
  saturation: 0.4738366110250354
  rhythmicContrast: 0.522592535475269
purpose: []
