name: adamvilliers
favicon: null
layout_spectrum: 0.31418726057745516
typography_spectrum: 0.2501019991468638
title: Welcome to Adam Villiers Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f4f0'
    - '#a1818e'
    - '#453737'
    - '#fe4f50'
    - '#7c5866'
  brandStrength: 0.5
  lightness: 0.7370277459267527
  saturation: 0.4738366110250354
  rhythmicContrast: 0.522592535475269
purpose: []
